# -----------------------------------------------------------------------------
# BUILD / DEPLOY (run from the directory containing this template.yaml)
#
# 1) Configure AWS credentials/profile as usual.
#
# 2) Deploy (guided the first time):
#      sam deploy --guided
#
#    Subsequent deploys:
#      sam deploy
#
# Notes:
# - This template creates networking (VPC + public subnet) for a quick start.
#   If you already have a VPC/subnet, you can replace the VPC/Subnet resources
#   with Parameters and wire them into the instance + security group.
#
# - DNS: Edit the DnsConfig mapping below to hard-code your HostedZoneId and base domain.
# -----------------------------------------------------------------------------


# Live:
#   sam sync
#

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Single EC2 instance + IAM access to DynamoDB + Route53 DNS A record to an Elastic IP.
  (No load balancer.)


Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        TABLE_PREFIX: !Ref TablePrefix

Parameters:
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for camera.planttracer.com (e.g., Z123ABC...)
    Default: "Z02875141U8JDG1N8N5BO"

  HostLabel:
    Type: String
    Description: "Hostname label only (e.g., 'app' -> app.example.com)."
    AllowedPattern: "^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$"

  BaseDomain:
    Type: String
    Description: "base domain in which the hostnames are created"
    Default: "planttracer.com"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "EC2 KeyPair name for SSH access."

  ImageBucketName:
    Type: String
    Default: planttracer2

  UbuntuAmiId:
    Type: AWS::EC2::Image::Id
    Description: "Ubuntu AMI ID (e.g., Ubuntu 22.04 or 24.04) for your region. Default is Ubuntu 24.04 arm for us-east-2"
    Default: ami-0999f93ce3bb94c61

  InstanceType:
    Type: String
    Default: t4g.small
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t4g.nano
      - t4g.micro
      - t4g.small
      - t4g.medium
    Description: "Choose an instance type compatible with your AMI architecture."

  GitRepoUrl:
    Type: String
    Description: "Git repository URL to clone on boot (e.g., https://github.com/user/repo.git)."

  GitBranch:
    Type: String
    Default: main
    Description: "Git branch/tag to checkout."

  GitRunPath:
    Type: String
    Default: "./etc/bootstrap.sh"
    Description: "Path inside repo to execute (e.g., ./run.sh or python3 app.py)."

  TablePrefix:
    Type: String
    Description: PlantTracer table prefix

  CertificateArn:
    Type: String
    Default: ""
    Description: "(Optional) Existing ACM certificate ARN for camera.planttracer.com. Leave blank to auto-create."

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues: [CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET]
    Description: Default LOG_LEVEL environment value for the function

Conditions:
  CreateAcmCert: !Equals [!Ref CertificateArn, ""]

Resources:
  # --- Minimal networking: VPC + one public subnet + IGW + route table ---
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.30.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.30.10.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-subnet"

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # --- Security Group: open 22/80/443 to the world (as requested) ---
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Open inbound 22,80,443 from the world (NOT recommended for SSH in production --- remove ssh rule and use aws ssm start-session to access instance)."
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # --- IAM: allow the instance to access the named DynamoDB table ---
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"

      Policies:
      - PolicyName: Ec2DdbAndS3Access
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
                - dynamodb:DescribeTable
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}users"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}users/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}unique_emails"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}unique_emails/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}api_keys"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}api_keys/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}courses"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}courses/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}movies"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}movies/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}movie_frames"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}movie_frames/index/*"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}logs"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TablePrefix}logs/index/*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${ImageBucketName}"
                - !Sub "arn:${AWS::Partition}:s3:::${ImageBucketName}/*"

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref Ec2Role]

  # --- Stable public IP + DNS name ---
  InstanceEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  DnsARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Type: A
      TTL: 30
      ResourceRecords:
        - !Ref InstanceEip

  # --- EC2 instance ---
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref UbuntuAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref Ec2InstanceProfile
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: [!Ref InstanceSecurityGroup]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-app"
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          set -euo pipefail
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y
          apt-get install -y git ca-certificates curl
          install -d -m 0755 /opt/gits
          if [ ! -d /opt/gits/webapp/.git ]; then
              git clone --branch "${GitBranch}" --depth 1 "${GitRepoUrl}" /opt/gits/webapp
          else
              cd /opt/gits/webapp
              git fetch --all --prune
              git checkout "${GitBranch}"
              git pull --ff-only
          fi
          cd /opt/gits/webapp
          chmod +x "${GitRunPath}" || true
          exec "${GitRunPath}"

  InstanceEipAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt InstanceEip.AllocationId
      InstanceId: !Ref AppInstance

  ################################################################
  ### Create the DynamoDB tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email_idx
          KeySchema:
            - AttributeName: email
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  UniqueEmailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}unique_emails"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  ApiKeysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}api_keys"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: api_key
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: api_key
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id_idx
          KeySchema:
            - AttributeName: user_id
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}courses"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: course_id
          AttributeType: S
        - AttributeName: course_key
          AttributeType: S
      KeySchema:
        - AttributeName: course_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: course_key_idx
          KeySchema:
            - AttributeName: course_key
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: course_id_idx
          KeySchema:
            - AttributeName: course_id
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  CourseUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}course_users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: course_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: course_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE

  MoviesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}movies"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: movie_id
          AttributeType: S
        - AttributeName: course_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: movie_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: course_id_idx
          KeySchema:
            - AttributeName: course_id
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: user_id_idx
          KeySchema:
            - AttributeName: user_id
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  MovieFramesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}movie_frames"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: movie_id
          AttributeType: S
        - AttributeName: frame_number
          AttributeType: N
      KeySchema:
        - AttributeName: movie_id
          KeyType: HASH
        - AttributeName: frame_number
          KeyType: RANGE

  LogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TablePrefix}logs"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: log_id
          AttributeType: S
        - AttributeName: ipaddr
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: course_id
          AttributeType: S
        - AttributeName: time_t
          AttributeType: N
      KeySchema:
        - AttributeName: log_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ipaddr_idx
          KeySchema:
            - AttributeName: ipaddr
              KeyType: "HASH"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [log_id]

        - IndexName: user_id_idx
          KeySchema:
            - AttributeName: user_id
              KeyType: "HASH"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [log_id]

        - IndexName: course_time_t_idx
          KeySchema:
            - AttributeName: course_id
              KeyType: "HASH"
            - AttributeName: course_time
              KeyType: "RANGE"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [log_id]




  ################################################################
  ### This is for the lambda that we created
  LambdaCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateAcmCert
    Properties:
      DomainName: !Sub "${HostLabel}-lambda.${BaseDomain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "${HostLabel}-lambda.${BaseDomain}"
          HostedZoneId: !Ref HostedZoneId

  HomeHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
      Domain:
        DomainName: !Sub "${HostLabel}-lambda.${BaseDomain}"
        CertificateArn: !If [CreateAcmCert, !Ref LambdaCertificate, !Ref CertificateArn]
        Route53:
          HostedZoneId: !Ref HostedZoneId

  LambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        RequirementsFile: requirements.txt   # relative to CodeUri (src/)
    Properties:
      Runtime: python3.13
      CodeUri: lambda-src/
      Handler: lambda_app.main.lambda_handler
      Timeout: 60
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}users"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}unique_emails"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}api_keys"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}courses"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}course_users"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}movies"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}movie_frames"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${TablePrefix}logs"
        - S3CrudPolicy:
            BucketName: !Ref ImageBucketName

      Events:
        AnyRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HomeHttpApi
            Path: /
            Method: ANY
            PayloadFormatVersion: "2.0"
        AnyProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref HomeHttpApi
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

Outputs:
  # Production-specific outputs
  ApiId:
    Description: HTTP API ID
    Value: !Ref HomeHttpApi
  LambdaFunction:
    Description: Camera Lambda function name
    Value: !Ref LambdaFunction
