env:
  browser: true
  es2021: true

extends: eslint:recommended

ignorePatterns: ["unzipit-worker.module.mjs", "unzipit.module.mjs"]

parserOptions:
  ecmaVersion: latest

overrides:
  - files: ["*.js"]
  - files: ["scripts/*.js"]
    env:
      node: true

rules:
  "no-unused-vars": ["error", { "args": "all", "argsIgnorePattern" : "^_" }]

globals:
  $: readonly
  $$: readonly
