#
# Read the docs:
# https://aws.amazon.com/blogs/compute/using-container-image-support-for-aws-lambda-with-aws-sam/

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planttracer-webapp

  SAM Template for planttracer-webapp. Uses docker.

Globals:
  Function:
    Timeout: 15
    MemorySize: 512
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image/x-icon
        - image/png
        - image/jpeg
        - audio/mpeg
        - application/octet-stream
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LAMBDA: "YES"
          DEBUG_DUMP_FILES: "NO"
          DEMO_MODE: "YES"
          ENCODE_BINARY_CONTENT: "YES"
          LOG_LEVEL: INFO
          PLANTTRACER_LOG_LEVEL: "WARNING"
          PLANTTRACER_S3_BUCKET: "planttracer-dev"
          PLANTTRACER_SMTP: "arn:aws:secretsmanager:us-east-1:376778049323:secret:planttracer_smtp-5TWQyf"
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          POWERTOOLS_SERVICE_NAME: FastAPI
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:376778049323:secret:planttracer_smtp-5TWQyf"
      Events:
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi # Link to the explicitly defined API
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi # Link to the explicitly defined API
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: python3.11-v1  # which tag to use
      DockerContext: ./deploy   # points to the folder containing the function code
      Dockerfile: Dockerfile    # identifies dockerfile for creating image

Outputs:
  ApiUrl:
    Description: "URL of the API Gateway Endpoint"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: ApiUrl

  HandlerFunctionArn:
    Description: "Mangum Handler Function ARN"
    Value: !GetAtt HandlerFunction.Arn
