AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planttracer-webapp

  SAM Template for planttracer-webapp

# https://stackoverflow.com/questions/67065130/how-to-enable-cors-with-aws-sam
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'content-type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Layers:
        - !Ref OpenCVLayer
      MemorySize: 512
      Timeout: 15
      Tracing: Active
      Environment:
        Variables:
          AWS_LAMBDA: "YES"
          DBREADER: "arn:aws:secretsmanager:us-east-1:376778049323:secret:planttracer_dbreader_prod-ui2Hf1"
          DBWRITER: "arn:aws:secretsmanager:us-east-1:376778049323:secret:planttracer_dbwriter_prod-OOt56r"
          PLANTTRACER_CREDENTIALS: "etc/credentials-aws-prod.ini"
          PLANTTRACER_SMTP: "arn:aws:secretsmanager:us-east-1:376778049323:secret:planttracer_smtp-5TWQyf"
          PLANTTRACER_LOG_LEVEL: "WARNING"
          POWERTOOLS_SERVICE_NAME: FastAPI
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Tags:
        LambdaPowertools: python

  OpenCVLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - arm64
      ContentUri: layer/

Outputs:
  ApiUrl:
    Description: "URL of the API Gateway Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: ApiUrl

  HandlerFunction:
    Description: "Mangum Handler Function ARN"
    Value: !GetAtt HandlerFunction.Arn
