"""
Ensure Lambda deployment will have runtime dependencies needed by lambda-resize.

The Lambda is built from lambda-resize/src/requirements.txt (generated by
poetry export --only main,lambda). Tracker code imports cv2 (opencv-python-headless).
If that package is missing from the export, the deployed Lambda fails at runtime
with "No module named 'cv2'".

This test fails if requirements.txt does not list opencv-python-headless, so that
make check catches the problem before deploy.
"""

import os

import pytest


REQUIREMENTS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "lambda-resize", "src", "requirements.txt"
)
REQUIRED_PACKAGES = ["opencv-python-headless"]


def test_lambda_requirements_include_tracker_deps():
    """Lambda requirements.txt must include opencv (cv2) for tracker/track-movie."""
    if not os.path.isfile(REQUIREMENTS_PATH):
        pytest.skip(f"Lambda requirements not found: {REQUIREMENTS_PATH}")
    with open(REQUIREMENTS_PATH, encoding="utf-8") as f:
        content = f.read()
    for pkg in REQUIRED_PACKAGES:
        assert pkg in content, (
            f"lambda-resize/src/requirements.txt must contain '{pkg}' "
            "(needed by tracker.py / track-movie). "
            "Run: poetry export --only main,lambda --format=requirements.txt "
            "--output lambda-resize/src/requirements.txt --without-hashes"
        )
