"""Integration coverage for the iOS camera movie finalization path."""

# pylint: disable=no-member  # cv2 exposes C extension members pylint cannot see

import os
import tempfile
from pathlib import Path

import cv2

from resize_app import camera_capture
from resize_app.src.app.odb import DDBO as ResizeDDBO

from app import mp4_metadata_lib, odb
from app.constants import storage_deployment_id
from app.s3_presigned import frame_object_key, make_urn, movie_object_key, parse_s3_urn, s3_client


def test_stop_assembles_uploaded_frames_and_processes_movie(
    new_movie_record, local_s3, request, monkeypatch,
):
    """STOP converts complete, ordered MinIO frames into a ready source movie."""
    monkeypatch.delenv("TRACING_QUEUE_MODE", raising=False)
    monkeypatch.delenv("TRACKING_QUEUE_MODE", raising=False)
    movie_id = new_movie_record[odb.MOVIE_ID]
    ddbo = new_movie_record["ddbo"]
    monkeypatch.setenv("DYNAMODB_TABLE_PREFIX", ddbo.table_prefix)
    monkeypatch.setattr(ResizeDDBO, "_instance", None)
    assert ResizeDDBO().table_prefix == ddbo.table_prefix
    assert ResizeDDBO().get_api_key_dict(new_movie_record[odb.API_KEY])
    course_id = new_movie_record[odb.COURSE_ID]
    deployment_id = storage_deployment_id()
    source_urn = make_urn(object_name=movie_object_key(
        deployment_id=deployment_id, course_id=course_id, movie_id=movie_id,
    ))
    ddbo.update_movie(movie_id, {
        odb.MOVIE_DATA_URN: source_urn,
        odb.CAMERA_CAPTURE: True,
        odb.FPM: "4",
    })

    bucket = os.environ[odb.C.PLANTTRACER_S3_BUCKET]
    assert local_s3 == bucket
    client = s3_client()
    frame_prefix = frame_object_key(
        deployment_id=deployment_id,
        course_id=course_id,
        movie_id=movie_id,
        frame_number=0,
    ).rsplit("/", 1)[0] + "/"

    def clean_camera_objects():
        """Remove the frame inputs and source generated by this isolated test."""
        paginator = client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=bucket, Prefix=frame_prefix):
            for item in page.get("Contents", []):
                client.delete_object(Bucket=bucket, Key=item["Key"])
        _bucket, source_key = parse_s3_urn(urn=source_urn)
        client.delete_object(Bucket=bucket, Key=source_key)

    request.addfinalizer(clean_camera_objects)
    for frame_number in range(1, 4):
        frame_path = Path("tests/data") / f"frame_{frame_number:04d}.jpg"
        key = frame_object_key(
            deployment_id=deployment_id,
            course_id=course_id,
            movie_id=movie_id,
            frame_number=frame_number - 1,
        )
        frame = cv2.imread(str(frame_path))
        frame = cv2.resize(frame, (640, 480))
        encoded, frame_bytes = cv2.imencode(".jpg", frame)
        assert encoded
        client.put_object(
            Bucket=bucket,
            Key=key,
            Body=frame_bytes.tobytes(),
            ContentType="image/jpeg",
        )

    result = camera_capture.finish(api_key=new_movie_record[odb.API_KEY], movie_id=movie_id)

    movie = ddbo.get_movie(movie_id)
    assert result == {"movie_id": movie_id, "status": odb.MOVIE_STATE_PROCESSING}
    assert movie[odb.MOVIE_STATUS] == odb.MOVIE_STATE_READY
    assert movie[odb.TOTAL_FRAMES] == 3
    assert movie[odb.ANALYSIS_MP4]

    bucket, key = parse_s3_urn(urn=source_urn)
    with tempfile.NamedTemporaryFile(suffix=".mov") as source_file:
        client.download_file(bucket, key, source_file.name)
        assert mp4_metadata_lib.get_fpm(source_file.name) == "4"
        assert mp4_metadata_lib.get_comment(source_file.name) == mp4_metadata_lib.RESEARCH_PROHIBITED
