"""Integration coverage for the iOS camera movie finalization path."""

# pylint: disable=no-member  # cv2 exposes C extension members pylint cannot see

import json
import os
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from threading import Barrier

import cv2
from resize_app import async_work, camera_capture
from resize_app.main import lambda_handler
from resize_app.src.app.odb import DDBO as ResizeDDBO

from app import mp4_metadata_lib, odb
from app.constants import storage_deployment_id
from app.s3_presigned import (
    frame_object_key,
    make_urn,
    movie_object_key,
    parse_s3_urn,
    s3_client,
)


class DummyContext:
    """Minimal Lambda context for API Gateway handler integration tests."""

    function_name = "test-finish-camera"
    memory_limit_in_mb = 128
    invoked_function_arn = "arn:aws:lambda:us-east-1:123456789012:function:test-finish-camera"
    aws_request_id = "test-request-id"


def _finish_camera_event(*, api_key=None, body=None):
    """Build an API Gateway v2 request for the camera STOP endpoint."""
    return {
        "version": "2.0",
        "routeKey": "POST /resize-api/v1/finish-camera",
        "rawPath": "/resize-api/v1/finish-camera",
        "rawQueryString": "",
        "headers": {"x-api-key": api_key} if api_key else {},
        "requestContext": {
            "stage": "$default",
            "http": {
                "method": "POST",
                "path": "/resize-api/v1/finish-camera",
                "sourceIp": "127.0.0.1",
            },
        },
        "body": "" if body is None else json.dumps(body),
        "isBase64Encoded": False,
    }


def _prepare_camera_movie(new_movie_record, local_s3, request, monkeypatch):
    """Store ordered camera frames for a local finalization test."""
    monkeypatch.delenv("TRACING_QUEUE_MODE", raising=False)
    monkeypatch.delenv("TRACKING_QUEUE_MODE", raising=False)
    movie_id = new_movie_record[odb.MOVIE_ID]
    ddbo = new_movie_record["ddbo"]
    monkeypatch.setenv("DYNAMODB_TABLE_PREFIX", ddbo.table_prefix)
    monkeypatch.setattr(ResizeDDBO, "_instance", None)
    assert ResizeDDBO().table_prefix == ddbo.table_prefix
    assert ResizeDDBO().get_api_key_dict(new_movie_record[odb.API_KEY])
    course_id = new_movie_record[odb.COURSE_ID]
    deployment_id = storage_deployment_id()
    source_urn = make_urn(object_name=movie_object_key(
        deployment_id=deployment_id, course_id=course_id, movie_id=movie_id,
    ))
    ddbo.update_movie(movie_id, {
        odb.MOVIE_DATA_URN: source_urn,
        odb.CAMERA_CAPTURE: True,
        odb.FPM: "4",
        odb.WIDTH: None,
        odb.HEIGHT: None,
        odb.FRAME_HEIGHT_PX: None,
    })

    bucket = os.environ[odb.C.PLANTTRACER_S3_BUCKET]
    assert local_s3 == bucket
    client = s3_client()
    frame_prefix = frame_object_key(
        deployment_id=deployment_id,
        course_id=course_id,
        movie_id=movie_id,
        frame_number=0,
    ).rsplit("/", 1)[0] + "/"

    def clean_camera_objects():
        """Remove the frame inputs and source generated by this isolated test."""
        paginator = client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=bucket, Prefix=frame_prefix):
            for item in page.get("Contents", []):
                client.delete_object(Bucket=bucket, Key=item["Key"])
        _bucket, source_key = parse_s3_urn(urn=source_urn)
        client.delete_object(Bucket=bucket, Key=source_key)

    request.addfinalizer(clean_camera_objects)
    for frame_number in range(1, 4):
        frame_path = Path("tests/data") / f"frame_{frame_number:04d}.jpg"
        key = frame_object_key(
            deployment_id=deployment_id,
            course_id=course_id,
            movie_id=movie_id,
            frame_number=frame_number - 1,
        )
        frame = cv2.imread(str(frame_path))
        frame = cv2.resize(frame, (640, 480))
        encoded, frame_bytes = cv2.imencode(".jpg", frame)
        assert encoded
        client.put_object(
            Bucket=bucket,
            Key=key,
            Body=frame_bytes.tobytes(),
            ContentType="image/jpeg",
        )
    return ddbo, movie_id, source_urn, bucket, client


def test_stop_assembles_uploaded_frames_and_processes_movie(
    new_movie_record, local_s3, request, monkeypatch,
):
    """STOP converts complete, ordered MinIO frames into a ready source movie."""
    ddbo, movie_id, source_urn, bucket, client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )

    response = lambda_handler(
        _finish_camera_event(
            api_key=new_movie_record[odb.API_KEY],
            body={"movie_id": movie_id},
        ),
        DummyContext(),
    )

    movie = ddbo.get_movie(movie_id)
    assert response["statusCode"] == 200
    assert json.loads(response["body"]) == {
        "error": False,
        "movie_id": movie_id,
        "status": odb.MOVIE_STATE_PROCESSING,
    }
    assert movie[odb.MOVIE_STATUS] == odb.MOVIE_STATE_READY
    assert movie[odb.TOTAL_FRAMES] == 3
    assert movie[odb.ANALYSIS_MP4]

    frame_prefix = frame_object_key(
        deployment_id=storage_deployment_id(),
        course_id=movie[odb.COURSE_ID],
        movie_id=movie_id,
        frame_number=0,
    ).rsplit("/", 1)[0] + "/"
    assert not client.list_objects_v2(Bucket=bucket, Prefix=frame_prefix).get("Contents")
    camera_capture.process(async_work.CameraMovieJob(movie_id=movie_id, attempt="duplicate"))
    assert not client.list_objects_v2(Bucket=bucket, Prefix=frame_prefix).get("Contents")

    bucket, key = parse_s3_urn(urn=source_urn)
    with tempfile.NamedTemporaryFile(suffix=".mov") as source_file:
        client.download_file(bucket, key, source_file.name)
        assert mp4_metadata_lib.get_fpm(source_file.name) == "4"
        assert mp4_metadata_lib.get_comment(source_file.name) == mp4_metadata_lib.RESEARCH_PROHIBITED


def test_finish_camera_rejects_missing_api_key():
    """The Lambda endpoint requires its API key before validating the request body."""
    response = lambda_handler(_finish_camera_event(body={"movie_id": "m123"}), DummyContext())

    assert response["statusCode"] == 401


def test_finish_camera_rejects_missing_movie_id():
    """The Lambda endpoint rejects an empty STOP request before movie lookup."""
    response = lambda_handler(_finish_camera_event(api_key="key"), DummyContext())

    assert response["statusCode"] == 400


def test_finish_camera_returns_forbidden_for_invalid_api_key(
    new_movie_record, local_s3, request, monkeypatch,
):
    """Invalid credentials keep the Lambda endpoint's authorization status."""
    _ddbo, movie_id, _source_urn, _bucket, _client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )
    response = lambda_handler(
        _finish_camera_event(api_key="invalid-key", body={"movie_id": movie_id}),
        DummyContext(),
    )

    assert response["statusCode"] == 403


def test_finish_camera_returns_conflict_for_stopped_movie(
    new_movie_record, local_s3, request, monkeypatch,
):
    """A valid caller receives 409 when the movie no longer accepts STOP."""
    ddbo, movie_id, _source_urn, _bucket, _client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )
    ddbo.update_movie(movie_id, {odb.MOVIE_STATUS: odb.MOVIE_STATE_READY})
    response = lambda_handler(
        _finish_camera_event(
            api_key=new_movie_record[odb.API_KEY],
            body={"movie_id": movie_id},
        ),
        DummyContext(),
    )

    assert response["statusCode"] == 409


def test_expired_camera_job_reclaims_processing_lease(new_movie_record, local_s3, request, monkeypatch):
    """An expired EventBridge delivery claims a fresh lease and completes the movie."""
    ddbo, movie_id, _source_urn, _bucket, _client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )
    old_attempt = ddbo.claim_movie_processing(movie_id)
    ddbo.update_movie(movie_id, {odb.PROCESSING_EXPIRES_AT: 0})

    camera_capture.process(async_work.CameraMovieJob(movie_id=movie_id, attempt=old_attempt))

    movie = ddbo.get_movie(movie_id)
    assert movie[odb.MOVIE_STATUS] == odb.MOVIE_STATE_READY
    assert movie[odb.TOTAL_FRAMES] == 3
    assert movie[odb.ANALYSIS_MP4]
    assert not movie.get(odb.PROCESSING_ATTEMPT)


def test_camera_job_retry_recovers_after_incomplete_frame_upload(
    new_movie_record, local_s3, request, monkeypatch,
):
    """A retry can finish a camera movie after a transient frame-read failure."""
    ddbo, movie_id, _source_urn, bucket, client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )
    movie = ddbo.get_movie(movie_id)
    attempt = ddbo.claim_movie_processing(movie_id)
    job = async_work.CameraMovieJob(movie_id=movie_id, attempt=attempt)
    missing_key = frame_object_key(
        deployment_id=storage_deployment_id(),
        course_id=movie[odb.COURSE_ID],
        movie_id=movie_id,
        frame_number=1,
    )
    missing_frame = cv2.imread(str(Path("tests/data") / "frame_0002.jpg"))
    missing_frame = cv2.resize(missing_frame, (640, 480))
    encoded, frame_bytes = cv2.imencode(".jpg", missing_frame)
    assert encoded
    client.delete_object(Bucket=bucket, Key=missing_key)

    try:
        camera_capture.process(job)
    except ValueError as exc:
        assert str(exc) == "Camera frame uploads are incomplete"
    else:
        raise AssertionError("incomplete camera frame sequence must fail")

    failed_movie = ddbo.get_movie(movie_id)
    assert failed_movie[odb.MOVIE_STATUS] == odb.MOVIE_STATE_PROCESSING_FAILED
    assert failed_movie[odb.PROCESSING_ATTEMPT] == attempt
    assert failed_movie[odb.PROCESSING_EXPIRES_AT] > int(time.time())

    client.put_object(
        Bucket=bucket,
        Key=missing_key,
        Body=frame_bytes.tobytes(),
        ContentType="image/jpeg",
    )
    camera_capture.process(job)

    movie = ddbo.get_movie(movie_id)
    assert movie[odb.MOVIE_STATUS] == odb.MOVIE_STATE_READY
    assert movie[odb.ANALYSIS_MP4]


def test_concurrent_stop_claim_returns_conflict(new_movie_record, local_s3, request, monkeypatch):
    """Two STOP requests with an uploading snapshot produce one success and one conflict."""
    ddbo, movie_id, _source_urn, _bucket, _client = _prepare_camera_movie(
        new_movie_record, local_s3, request, monkeypatch,
    )
    validate_movie_access = camera_capture.movie_glue.validate_movie_access
    both_validated = Barrier(2)

    def synchronized_validate_movie_access(*, api_key, movie_id, require_edit=False):
        result = validate_movie_access(api_key=api_key, movie_id=movie_id, require_edit=require_edit)
        both_validated.wait(timeout=10)
        return result

    monkeypatch.setattr(
        camera_capture.movie_glue, "validate_movie_access", synchronized_validate_movie_access,
    )

    def stop_recording():
        try:
            return camera_capture.finish(api_key=new_movie_record[odb.API_KEY], movie_id=movie_id)
        except ValueError as exc:
            return exc

    with ThreadPoolExecutor(max_workers=2) as pool:
        results = list(pool.map(lambda _index: stop_recording(), range(2)))

    assert sum(isinstance(result, ValueError) for result in results) == 1
    assert ddbo.get_movie(movie_id)[odb.MOVIE_STATUS] == odb.MOVIE_STATE_READY
