"""
Run the PlantTracer tracing pipeline locally against DynamoDB Local + MinIO.
"""

from __future__ import annotations

import argparse
import json
import os
import uuid
from contextlib import suppress
from decimal import Decimal
from pathlib import Path
from typing import Any

from botocore.exceptions import ClientError
from resize_app import movie_glue

from app import odb
from app import odbmaint
from app import odb_movie_data
from app.constants import C
from app.constants import configure_local_environment as configure_shared_local_environment
from app.odb import (
    COURSE_ID,
    COURSE_KEY,
    DDBO,
    FRAME_NUMBER,
    FRAME_URN,
    MOVIE_ID,
    MOVIE_TRACED_URN,
    MOVIE_ZIPFILE_URN,
    ODB_Errors,
    USER_ID,
)
from app.s3_presigned import s3_client
from app.schema import Trackpoint


def ensure_local_backing_services() -> None:
    """Ensure the local tables and bucket exist before we seed a tracing run."""
    odbmaint.create_tables(ignore_table_exists=True)
    bucket = os.environ[C.PLANTTRACER_S3_BUCKET]
    client = s3_client()
    try:
        client.head_bucket(Bucket=bucket)
    except ClientError as exc:
        error_code = exc.response.get("Error", {}).get("Code")
        if error_code in {"404", "NoSuchBucket", "NotFound"}:
            client.create_bucket(Bucket=bucket)
        else:
            raise


def decimal_to_number(value: Any) -> Any:
    if isinstance(value, Decimal):
        if value == value.to_integral_value():
            return int(value)
        return float(value)
    return value


def serialize_trackpoint(trackpoint: dict[str, Any]) -> dict[str, Any]:
    serialized = {}
    for key, value in trackpoint.items():
        if value is None:
            continue
        serialized[key] = decimal_to_number(value)
    return serialized


def serialize_frame_record(frame: dict[str, Any]) -> dict[str, Any]:
    record = {
        MOVIE_ID: frame[MOVIE_ID],
        FRAME_NUMBER: int(frame[FRAME_NUMBER]),
    }
    if FRAME_URN in frame and frame[FRAME_URN] is not None:
        record[FRAME_URN] = frame[FRAME_URN]
    if "trackpoints" in frame:
        record["trackpoints"] = [serialize_trackpoint(tp) for tp in frame["trackpoints"]]
    return record


def load_trackpoint_records(path: Path) -> list[dict[str, Any]]:
    raw = json.loads(path.read_text())
    if not isinstance(raw, list):
        raise ValueError("Trackpoint JSON must be an array of DynamoDB movie_frames records")

    records: list[dict[str, Any]] = []
    for item in raw:
        if not isinstance(item, dict):
            raise ValueError("Each frame record must be a JSON object")
        if FRAME_NUMBER not in item:
            raise ValueError("Each frame record must include frame_number")
        trackpoints = item.get("trackpoints")
        if not isinstance(trackpoints, list) or len(trackpoints) == 0:
            raise ValueError("Each frame record must include a non-empty trackpoints array")
        records.append({
            FRAME_NUMBER: int(item[FRAME_NUMBER]),
            "trackpoints": [Trackpoint(**trackpoint) for trackpoint in trackpoints],
        })

    records.sort(key=lambda record: record[FRAME_NUMBER])
    return records


def create_cli_scaffold(movie_title: str) -> dict[str, str]:
    suffix = uuid.uuid4().hex[:8]
    course_id = f"local-trace-{suffix}"
    course_key = f"local-trace-{uuid.uuid4().hex}"
    user_email = f"local-trace-{suffix}@example.com"
    user_name = "Local Trace CLI"

    odb.create_course(course_id=course_id, course_name="Local Trace CLI", course_key=course_key, ok_if_exists=False)
    user_id = odb.register_email(email=user_email, user_name=user_name, course_id=course_id)[USER_ID]
    movie_id = odb.create_new_movie(
        user_id=user_id,
        course_id=course_id,
        title=movie_title,
        description="Local tracing run generated by planttracer-local-trace",
    )
    return {
        COURSE_ID: course_id,
        COURSE_KEY: course_key,
        USER_ID: user_id,
        MOVIE_ID: movie_id,
    }


def cleanup_cli_scaffold(ids: dict[str, str]) -> None:
    movie_id = ids.get(MOVIE_ID)
    user_id = ids.get(USER_ID)
    course_id = ids.get(COURSE_ID)
    ddbo = DDBO()

    if movie_id:
        with suppress(ClientError, ODB_Errors, RuntimeError, ValueError):
            odb_movie_data.purge_movie(movie_id=movie_id)
        with suppress(ClientError, ODB_Errors, RuntimeError, ValueError):
            ddbo.batch_delete_movie_ids([movie_id])
    if user_id:
        with suppress(ClientError, ODB_Errors, RuntimeError, ValueError):
            odb.delete_user(user_id=user_id, purge_movies=False)
    if course_id:
        with suppress(ClientError, ODB_Errors, RuntimeError, ValueError):
            odb.delete_course(course_id=course_id)


def write_outputs(*, movie_id: str, output_dir: Path, output_prefix: str, write_zip: bool) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    metadata = odb.get_movie_metadata(movie_id=movie_id, get_last_frame_tracked=True)
    frames = DDBO().get_frames(movie_id)
    frames_with_trackpoints = [frame for frame in frames if "trackpoints" in frame]
    frames_with_trackpoints.sort(key=lambda frame: int(frame[FRAME_NUMBER]))

    json_path = output_dir / f"{output_prefix}-trackpoints.json"
    json_path.write_text(json.dumps([serialize_frame_record(frame) for frame in frames_with_trackpoints], indent=2))

    mp4_path = output_dir / f"{output_prefix}-traced.mp4"
    traced_urn = metadata.get(MOVIE_TRACED_URN)
    if not traced_urn:
        raise RuntimeError("Tracing completed without a traced movie URN")
    odb_movie_data.copy_object_to_path(traced_urn, str(mp4_path))

    outputs = {
        "json": json_path,
        "mp4": mp4_path,
    }

    if write_zip:
        zip_urn = metadata.get(MOVIE_ZIPFILE_URN)
        if not zip_urn:
            raise RuntimeError("Tracing completed without a zipfile URN")
        zip_path = output_dir / f"{output_prefix}-frames.zip"
        odb_movie_data.copy_object_to_path(zip_urn, str(zip_path))
        outputs["zip"] = zip_path

    return outputs


def run_local_trace(args: argparse.Namespace) -> int:
    configure_shared_local_environment()
    ensure_local_backing_services()

    movie_path = args.movie_file.resolve()
    trackpoints_path = args.trackpoints_json.resolve()
    frame_records = load_trackpoint_records(trackpoints_path)
    source_frame = args.source_frame
    if source_frame is None:
        source_frame = max(record[FRAME_NUMBER] for record in frame_records)
    if source_frame not in {record[FRAME_NUMBER] for record in frame_records}:
        raise ValueError(f"source_frame {source_frame} is not present in {trackpoints_path}")

    output_dir = args.output_dir.resolve()
    output_prefix = args.output_prefix or movie_path.stem

    ids: dict[str, str] = {}
    try:
        ids = create_cli_scaffold(args.movie_title or movie_path.stem)
        movie_id = ids[MOVIE_ID]
        odb_movie_data.set_movie_data(movie_id=movie_id, movie_data=movie_path.read_bytes())
        for record in frame_records:
            odb.put_frame_trackpoints(
                movie_id=movie_id,
                frame_number=record[FRAME_NUMBER],
                trackpoints=record["trackpoints"],
            )

        movie_glue.run_tracing(movie_id=movie_id, frame_start=source_frame)
        outputs = write_outputs(
            movie_id=movie_id,
            output_dir=output_dir,
            output_prefix=output_prefix,
            write_zip=not args.no_output_zip,
        )

        print(f"movie_id={movie_id}")
        print(f"source_frame={source_frame}")
        print(f"trackpoints_json={outputs['json']}")
        print(f"traced_movie={outputs['mp4']}")
        if "zip" in outputs:
            print(f"zipfile={outputs['zip']}")
        if args.no_cleanup:
            print("cleanup=skipped")
            print(f"course_id={ids[COURSE_ID]}")
            print(f"user_id={ids[USER_ID]}")
        return 0
    finally:
        if ids and not args.no_cleanup:
            cleanup_cli_scaffold(ids)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="planttracer-local-trace",
        description="Seed a local movie + frame records, run tracing locally, and export the results.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("movie_file", type=Path, help="Movie file to upload into local MinIO")
    parser.add_argument("trackpoints_json", type=Path, help="JSON array of movie_frames-style DynamoDB records")
    parser.add_argument("--source-frame", type=int, default=None,
                        help="Edited source frame. Defaults to the highest frame_number present in the JSON input")
    parser.add_argument("--movie-title", type=str, default=None, help="Title to store on the temporary movie record")
    parser.add_argument("--output-dir", type=Path, default=Path.cwd(), help="Directory for exported artifacts")
    parser.add_argument("--output-prefix", type=str, default=None, help="Prefix for exported artifact filenames")
    parser.add_argument("--no-cleanup", action="store_true",
                        help="Leave the temporary DynamoDB records and MinIO objects in place for debugging")
    parser.add_argument("--no-output-zip", action="store_true",
                        help="Do not export the generated frame zipfile alongside the traced movie")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return run_local_trace(args)


if __name__ == "__main__":
    raise SystemExit(main())
