#
# Development is done with browser-sync

run:
	browser-sync start --server --files "*.html, *.css, *.js"

run-proxy-local:
	@echo useful for injecting into a proxy running
	browser-sync start --proxy "localhost:5000" --files "*.html, *.css, *.js"


run-proxy-app:
	@echo useful for injecting into a proxy running
	browser-sync start --proxy "localhost:5000" --files "*.html, *.css, *.js"


install:
	npm install -g browser-sync
