# https://coderefinery.github.io/documentation/gh_workflow/
name: doctest

# This workflow is for testing out documentation builds while working in branches

# Really the only differences between this and documentation.yml are:
# 1) trigger conditions (on)
# 2) publish to the gh-pages-test branch, not gh-pages
# 3) deployment isn't conditional on the branch being 'main'
#
# Beware of this file getting out of sync with documentation.yml. Might be easier to just
# copy and edit from documentation.yml each time!

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
